export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USERNAME_IS_AVAILABLE = 'USERNAME_IS_AVAILABLE';
export const USERNAME_IS_NOT_AVAILABLE = 'USERNAME_IS_NOT_AVAILABLE';
export const USERNAME_IS_TOO_SHORT = 'USERNAME_IS_TOO_SHORT';
export const USERNAME_IS_TOO_LONG = 'USERNAME_IS_TOO_LONG';
export const USERNAME_IS_VALIDATING = 'USERNAME_IS_VALIDATING';

export const EMAIL_IS_AVAILABLE = 'EMAIL_IS_AVAILABLE';
export const EMAIL_IS_NOT_AVAILABLE = 'EMAIL_IS_NOT_AVAILABLE';
export const EMAIL_IS_EMPTY = 'EMAIL_IS_EMPTY';
export const EMAIL_IS_INVALID = 'EMAIL_IS_INVALID';
export const EMAIL_IS_TOO_LONG = 'EMAIL_IS_TOO_LONG';
export const EMAIL_IS_VALIDATING = 'EMAIL_IS_VALIDATING';
